// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1oUk-ekKX7T_FZF8rT3ovQYaTCj6Oyk',
    appId: '1:4245962162:web:5ca6a33e05a7b5b2fcf8ab',
    messagingSenderId: '4245962162',
    projectId: 'solar-application-56720',
    authDomain: 'solar-application-56720.firebaseapp.com',
    storageBucket: 'solar-application-56720.firebasestorage.app',
    measurementId: 'G-QTZ7N3P7FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdNADcvhyffkE-bBz06id-pLYWq1dzcE',
    appId: '1:4245962162:android:1f8950fe5a6e8c8cfcf8ab',
    messagingSenderId: '4245962162',
    projectId: 'solar-application-56720',
    storageBucket: 'solar-application-56720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWtyRMMvNdKfB-Swd4JglbCw3H_85yl4',
    appId: '1:4245962162:ios:674e67fb74788ca8fcf8ab',
    messagingSenderId: '4245962162',
    projectId: 'solar-application-56720',
    storageBucket: 'solar-application-56720.firebasestorage.app',
    iosBundleId: 'com.example.solarApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfWtyRMMvNdKfB-Swd4JglbCw3H_85yl4',
    appId: '1:4245962162:ios:674e67fb74788ca8fcf8ab',
    messagingSenderId: '4245962162',
    projectId: 'solar-application-56720',
    storageBucket: 'solar-application-56720.firebasestorage.app',
    iosBundleId: 'com.example.solarApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1oUk-ekKX7T_FZF8rT3ovQYaTCj6Oyk',
    appId: '1:4245962162:web:1dbc5bf2a6201d0dfcf8ab',
    messagingSenderId: '4245962162',
    projectId: 'solar-application-56720',
    authDomain: 'solar-application-56720.firebaseapp.com',
    storageBucket: 'solar-application-56720.firebasestorage.app',
    measurementId: 'G-NN9R6FKNSQ',
  );
}
